version: '2.1'
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    executor:
      name: python/default
      tag: '3.10'

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: run tests
          command: |
            poetry run pytest --junitxml=reports/junit/junit.xml tests ;
            poetry run genbadge tests -o badges/tests.svg
      - run:
          name: get coverage
          command: |
            poetry run coverage xml -o reports/coverage/coverage.xml ;
            poetry run genbadge coverage -o badges/coverage.svg

      - store_artifacts:
          path: reports

      - store_artifacts:
          path: badges

workflows:
  main:
    jobs:
      - build
